server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mingrui:
  upload:
    path:
      windows: D:\\images
      linux: /hh/images
    img:
      host: http://49.232.110.103/